### ISSUE TITLE
Application at context path /hapi-fhir-jpaserver could not be started 

### ISSUE THREAD

**Issue by loganthomison** [jamesagnew/hapi-fhir#105]
I've deployed a local server using the vagrant instructions. Everything works fine, but I cannot start hapi-fhir in tomcat. I see the following error in the logs.

INFO: validateJarFile(/var/lib/tomcat7/webapps/hapi-fhir-jpaserver/WEB-INF/lib/javax.el-api-3.0.0.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/el/Expression.class
Feb 10, 2015 5:01:50 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Feb 10, 2015 5:01:50 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/hapi-fhir-jpaserver] startup failed due to previous errors
Feb 10, 2015 5:01:50 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/restful-server-example.war
Feb 10, 2015 5:01:51 PM org.apache.catalina.loader.WebappClassLoader validateJarFile
INFO: validateJarFile(/var/lib/tomcat7/webapps/restful-server-example/WEB-INF/lib/javax.el-3.0.0.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/el/Expression.class

**Comment by josealmeida** [comment]
having the same problem. diving into the logs I also see: 

~~~
fhir.logdir_IS_UNDEFINED/access.%d{yyyy-MM-dd}.log for the active file
15:59:39,614 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern 'fhir.logdir_IS_UNDEFINED/access.%d{yyyy-MM-dd}.log.gz'.
15:59:39,614 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
15:59:39,614 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Mon Feb 16 15:59:39 UTC 2015
15:59:39,615 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:59:39,615 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ACCESS] - Active log file name: fhir.logdir_IS_UNDEFINED/access.log
15:59:39,615 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ACCESS] - File property is set to [fhir.logdir_IS_UNDEFINED/access.log]
15:59:39,615 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[ACCESS] - Failed to create parent directories for [/var/lib/tomcat7/fhir.logdir_IS_UNDEFINED/access.log]
15:59:39,615 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[ACCESS] - openFile(fhir.logdir_IS_UNDEFINED/access.log,true) call failed. java.io.FileNotFoundException: fhir.logdir_IS_UNDEFINED/access.log (No such file or directory)
	at java.io.FileNotFoundException: fhir.logdir_IS_UNDEFINED/access.log (No such file or directory)
~~~

In my case it seems to be a log path issue

**Comment by jamesagnew** [comment]
Can you do a pull and rebuild, then try again? I think things should be fixed.
We had a reference to the old "dev" structures that needed to be renamed to "dstu2".

I've also added a new, more useful server to the vagrant install at:
http://localhost:[vagrant port]/hapi-fhir-jpaserver-example/

**Comment by llazarre** [comment]
I was experiencing the same issue. I did a pull and rebuild as advised. I am now able to start hapi-fhir-jpaserver. However, the context problem remains for all the other applications: hapi-fhir-jpaserver-example, restful-server-example, hapi-fhir-testpage-overlay-0.9-SNAPSHOT. Even though the .wars have been deployed and the applications are running on the Tomcat admin console, they all return the following exception: Request processing failed; nested exception is ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException: HTTP 404 Not Found

Please review and advise. Thanks.
