### ISSUE TITLE
Extension for contained resource Reference does not serialize to JSON or XML properly. 

### ISSUE THREAD

**Issue by fw060** [jamesagnew/hapi-fhir#327]
See the following test code: 

```
@ResourceDef(name="Patient")
public class TestPatient extends Patient
{

	@Child(name = "testCondition")
    @Extension(url="testCondition", definedLocally=true, isModifier=false)
	private List<Reference> testConditions = null;
	
	public void setCondition(List<Reference> ref)
	{
		this.testConditions = ref;
	}
	
	public List<Reference> getConditions()
	{
		return this.testConditions;
	}
}
```

PatientProvider class: 
```
	@Read()
	public Patient read(@IdParam IdType theId) {
		
		
		TestPatient patient = new TestPatient();
		patient.setBirthDate(new Date());
		
		List<Reference> conditions = new ArrayList<>();
		conditions.add(new Reference(new Condition()));
		patient.setCondition(conditions);
		
		
		return patient;
	}


```

Test result is :
```
{
  "resourceType": "Patient",
  "extension": [
    {
      "url": "testCondition",
      "valueReference": {}
    }
  ],
  "contained": [
    {
      "resourceType": "Condition",
      "id": "1"
    }
  ],
  "birthDate": "2016-04-06"
}
```

**Comment by fw060** [comment]
The following code fixed it, but the code can use more optimization:

```
diff --git a/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/RuntimeChildDeclaredExtensionDefinition.java b/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/RuntimeChildDeclaredExtensionDefinition.java
index 60a2786..20a5c74 100644
--- a/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/RuntimeChildDeclaredExtensionDefinition.java
+++ b/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/RuntimeChildDeclaredExtensionDefinition.java
@@ -159,12 +159,12 @@ public class RuntimeChildDeclaredExtensionDefinition extends BaseRuntimeDeclared
                BaseRuntimeElementDefinition<?> elementDef = theClassToElementDefinitions.get(myChildType);
                if (elementDef instanceof RuntimePrimitiveDatatypeDefinition || elementDef instanceof RuntimeCompositeDatatypeDefinition) {
                        myDatatypeChildName = "value" + elementDef.getName().substring(0, 1).toUpperCase() + elementDef.getName().substring(1);
-                       if ("valueResourceReference".equals(myDatatypeChildName)) {
+                       if ("valueReference".equals(myDatatypeChildName)) {
                                // Per one of the examples here: http://hl7.org/implement/standards/fhir/extensibility.html#extension
                                myDatatypeChildName = "valueResource";
                                List<Class<? extends IBaseResource>> types = new ArrayList<Class<? extends IBaseResource>>();
                                types.add(IResource.class);
-                               myChildDef = new RuntimeResourceReferenceDefinition("valueResource", types, false);
+                               myChildDef = new RuntimeResourceReferenceDefinition("valueReference", types, false);
                        } else {
                                myChildDef = elementDef;
                        }

```

Test result is:
```
{
  "resourceType": "Patient",
  "extension": [
    {
      "url": "testCondition",
      "valueResource": {
        "reference": "#1"
      }
    }
  ],
  "contained": [
    {
      "resourceType": "Condition",
      "id": "1"
    }
  ],
  "birthDate": "2016-04-06"
}
```

**Comment by jamesagnew** [comment]
This was fixed as a result of a recent checkin, and should work correctly as a part of 1.5. Are you able to verify using a 1.5 snapshot build?

**Comment by fw060** [comment]
Sorry I wasn't verify this yet. We are not fully committed to use 1.5 yet. Which check in are you referring to? 

Thanks,
Fei

**Comment by fw060** [comment]
We upgraded to 1.6 and unfortunately this is still not fixed.

**Comment by jamesagnew** [comment]
Hi Fei,

Is it possible you have an old version of HAPI on your classpath?

We have your test case embedded basically verbatim in a unit test and it seems to pass. See [XmlParserDstu3Test.java's testEncodeExtensionWithContainedResource method](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-structures-dstu3/src/test/java/ca/uhn/fhir/parser/XmlParserDstu3Test.java#L1421)

Do you see any obvious differences between this test and your issue?

**Comment by fw060** [comment]
More tests shows that XML format does work, but not JSON format. I will work on a new fix. At the same time if you have any suggestion, please let me know.

**Comment by jamesagnew** [comment]
Ahh I just tried it in JSON and I see it too

**Comment by fw060** [comment]
yes, unfortunately my original fix no longer works. I am trying to figure out the new fix, but hopefully you have some quick insight :)

**Comment by jamesagnew** [comment]
Good news actually. I figured it out... Fix coming up soon :)

**Comment by fw060** [comment]
Awesome!!!

**Comment by fw060** [comment]
Another related question, is there any chance we can get a patch release 1.6.1? A strategy to have a patch release would greatly help people who use the library in production. Otherwise, we have to create a customized version :(

**Comment by jamesagnew** [comment]
Unfortunately we just don't have the capacity to do backported patches.. The backlog of fixes and enhancements on trunk is already more than we seem to be able to keep up with these days given how fast FHIR itself is changing :(

The change will be in a single commit though, so you should be able to cherry-pick and apply it to a checkout of any arbitrary version in a fork if you need to.

**Comment by fw060** [comment]
Thanks James! The signature of preProcessValues() changed, so I have to remove the last argument, but after that, your fix works for 1.6 too!

I understand your challenge on keeping up the FHIR spec change. Hopefully STU3 will be stable soon. That would benefit everyone :)

Again, thank a lot for the great work!
