### ISSUE TITLE
not forwarding POST parameters when _format is provided as a URL param on _search

### ISSUE THREAD

**Issue by jimsteel** [jamesagnew/hapi-fhir#411]
When POSTing a request to _search with a _format URL parameter (e.g. base/CodeSystem/_search?_format=application/xml), the parameters included in the POST body are not being provided to our method annotated with @Search

**Comment by jamesagnew** [comment]
Hi Jim, I just tried to reproduce this but it seems like it's working to me. Are you able to glance at the test I committed to see if it is missing any nuance from your circumstance?

**Comment by jimsteel** [comment]
I still don't really understand what the distinction is between the test case (which looks good) and my use case, but I'm seeing, for example,

`curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control: no-cache" -d 'name=Smith' "http://fhirtest.uhn.ca/baseDstu3/CodeSystem/_search?_format=application/json"`

giving a different result to

`curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control: no-cache" -d 'name=Smith' "http://fhirtest.uhn.ca/baseDstu3/CodeSystem/_search"`

**Comment by jamesagnew** [comment]
Fascinating. I see what you mean, and I get different results too between those command lines.. but even using those exact commands in a unit test doesn't seem to yield different results.

Are you seeing this issue on other servers than fhirtest.uhn.ca? I'm wondering if maybe the Apache reverse proxy is monkeying with the request.

**Comment by jimsteel** [comment]
Yeah, I'm seeing the same behaviour in our product not behind any proxy.

**Comment by jamesagnew** [comment]
Ahhhh victory. I figured it out.

The RestfulServer does its own parsing of urlencoded data (the request URL and the POST body) because a few servers (Tomcat and Glassfish) parse using ISO-8859/1 instead of UTF-8, so we don't want to rely on their parse logic. 

The issue was that some interceptors were "consuming" the request body before the server had a chance to look at it. I have a fix I'll check in as soon as the tests pass...

**Comment by lawley** [comment]
That's great news, thanks James.

Can you comment further on the ISO-8859/1 issue? Is that tomcat/glassfish picking up the environment default or is it something else?

**Comment by jamesagnew** [comment]
I don't remember all of the details of my investigation at the time.. but IIRC Tomcat and Glassfish (same underlying codebase for the HTTP stack which is why they do it the same) just used 8859-1 hard coded. I remember reproducing that issue on my Mac, where the platform default is UTF-8.

Ahh, just checked and sure enough I remember right: https://tomcat.apache.org/tomcat-6.0-doc/config/http.html (search for 8859-1)
