### ISSUE TITLE
Dstu2 pagination for patient resource is missing some entries

### ISSUE THREAD

**Issue by swethaborra** [jamesagnew/hapi-fhir#616]
we are using hapi-fhir server Dstu2. trying to pagination for patient resources

GET http://localhost:8080/hapi-fhir/baseDstu2/Patient returns 10 patients
when I go  to next page:
GET http://localhost:8080/hapi-fhir/baseDstu2?_getpages=cc76e8e1-070c-4b48-baa7-5a866648ec5f&_getpagesoffset=10&_count=10&_format=json&_pretty=true&_bundletype=searchset

it gives last two records of previous page and 8 new patients. 2 patient resources which are supposed to come are missing..if you have any suggestions could you please let us know.

Thanks!

**Comment by jamesagnew** [comment]
This sounds like an issue that was fixed in HAPI 2.3. Can you confirm whether this happens using the latest version of HAPI?

**Comment by swethaborra** [comment]
thank you for your response. we haven't upgraded to 2.3 yet. I will check when we upgrade and let you know.
Thanks!

**Comment by sirarthurmoney** [comment]
I'm currently using HAPI 2.3 today and am still having the same issue as swethaborra. Any suggestions?
